spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/railconnect
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=RailConnectSuperSecretKeyForJwtAuthenticationThatMustBeAtLeast256BitsLong!
jwt.expiration=86400000

# Server port
server.port=8080

logging.level.org.springframework.security=DEBUG

# Show default exception messages in API responses
server.error.include-message=always
